apiVersion: v1
kind: ConfigMap
metadata:
  name: getttright-configmap
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
  CONFIGSERVER_APPLICATION_NAME: "configserver"
  EUREKA_APPLICATION_NAME: "eurekaserver"
  ACCOUNTS_APPLICATION_NAME: "accounts"
  ACCOUNTS_SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3307/accountsdb"
  LOANS_APPLICATION_NAME: "loans"
  LOANS_SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3309/loansdb"
  CARDS_APPLICATION_NAME: "cards"
  CARDS_SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3308/cardsdb"
  GATEWAY_APPLICATION_NAME: "gatewayserver"
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
